export const cerCirSpecialCases = [
  { sp: "agradecer", en: "to thank" },
  { sp: "aparecer", en: "to appear" },
  { sp: "conocer", en: "to know, to be aquainted with (a person)" },
  { sp: "desaparecer", en: "to disappear" },
  { sp: "desconocer", en: "to be ignorant of" },
  { sp: "establecer", en: "to establish" },
  { sp: "merecer", en: "to deserve" },
  { sp: "crecer", en: "" },
  { sp: "nacer", en: "" },
  { sp: "conocer", en: "" },
  { sp: "producir", en: "" },
  { sp: "yacer", en: "" },
  { sp: "", en: "" },
  { sp: "obedecer", en: "to obey" },
  { sp: "ofrecer", en: "to offer" },
  { sp: "permanecer", en: "to remain" },
  { sp: "pertenecer", en: "to belong" },
  { sp: "introducir", en: "to introduce" },
];

export const partialIarVerbList = [
  { sp: "aliar", en: "to ally" },
  { sp: "ampliar", en: "to expand, amplify" },
  { sp: "autografiar", en: "to autograph" },
  { sp: "criar", en: "to breed, raise" },
  { sp: "desafiar", en: "to challenge" },
  { sp: "desliar", en: "to untie" },
  { sp: "desviar", en: "to divert" },
  { sp: "enfriar", en: "to chill" },
  { sp: "enviar", en: "to send" },
  { sp: "espiar", en: "to spy" },
  { sp: "fiar", en: "to confide" },
  { sp: "fotografiar", en: "to photograph" },
  { sp: "guiar", en: "to guide" },
  { sp: "liar", en: "to bundle" },
  { sp: "malcriar", en: "to pamper" },
  { sp: "resfriar", en: "to cool" },
  { sp: "rociar", en: "to sprinkle" },
  { sp: "vaciar", en: "to empty" },
  { sp: "variar", en: "to vary" },
];

export const irregularVerbs = [
  "aburrirse",
  "abastecer",
  "abolir",
  "aborrecer",
  "abrir",
  "abstenerse",
  "abstraer",
  "acaecer",
  "acertar",
  "acontecer",
  "acordar",
  "acostar",
];
