export const cerCirSpecialCases = [
  { sp: "agradecer", en: "to thank" },
  { sp: "aparecer", en: "to appear" },
  { sp: "conocer", en: "to know, to be aquainted with (a person)" },
  { sp: "desaparecer", en: "to disappear" },
  { sp: "desconocer", en: "to be ignorant of" },
  { sp: "establecer", en: "to establish" },
  { sp: "merecer", en: "to deserve" },
  { sp: "crecer", en: "" },
  { sp: "nacer", en: "" },
  { sp: "conocer", en: "" },
  { sp: "producir", en: "" },
  { sp: "yacer", en: "" },
  { sp: "", en: "" },
  { sp: "obedecer", en: "to obey" },
  { sp: "ofrecer", en: "to offer" },
  { sp: "permanecer", en: "to remain" },
  { sp: "pertenecer", en: "to belong" },
  { sp: "introducir", en: "to introduce" },
];

export const partialIarVerbList = [
  { sp: "aliar", en: "to ally" },
  { sp: "ampliar", en: "to expand, amplify" },
  { sp: "autografiar", en: "to autograph" },
  { sp: "criar", en: "to breed, raise" },
  { sp: "desafiar", en: "to challenge" },
  { sp: "desliar", en: "to untie" },
  { sp: "desviar", en: "to divert" },
  { sp: "enfriar", en: "to chill" },
  { sp: "enviar", en: "to send" },
  { sp: "espiar", en: "to spy" },
  { sp: "fiar", en: "to confide" },
  { sp: "fotografiar", en: "to photograph" },
  { sp: "guiar", en: "to guide" },
  { sp: "liar", en: "to bundle" },
  { sp: "malcriar", en: "to pamper" },
  { sp: "resfriar", en: "to cool" },
  { sp: "rociar", en: "to sprinkle" },
  { sp: "vaciar", en: "to empty" },
  { sp: "variar", en: "to vary" },
];

export const irregularVerbs = [
  "aburrirse",
  "abastecer",
  "abolir",
  "aborrecer",
  "abrir",
  "abstenerse",
  "abstraer",
  "acaecer",
  "acertar",
  "acontecer",
  "acordar",
  "acostar",
];

export const uarVerbs = [
  { sp: "acentuar", en: "to emphasize, accentuate" },
  { sp: "actuar", en: "to act" },
  { sp: "atenuar", en: "to attenuate" },
  { sp: "conceptuar", en: "to deem" },
  { sp: "continuar", en: "to continue" },
  { sp: "desvirtuar", en: "to spoil" },
  { sp: "efectuar", en: "to carry out, effect" },
  { sp: "evaluar", en: "to assess, evaluate" },
  { sp: "exceptuar", en: "to except" },
  { sp: "extenuar", en: "to emaciate" },
  { sp: "fluctuar", en: "to fluctuate" },
  { sp: "graduar", en: "to grade" },
  { sp: "habituar", en: "to habituate" },
  { sp: "individuar", en: "to individualize" },
  { sp: "infatuar", en: "to infatuate" },
  { sp: "insinuar", en: "to hint, insinuate" },
  { sp: "menstruar", en: "to menstruate" },
  { sp: "perpetuar", en: "to perpetuate" },
  { sp: "preceptuar", en: "to establish, lay down" },
  { sp: "puntuar", en: "to punctuate, to assess" },
  { sp: "redituar", en: "to yield (a profit)" },
  { sp: "situar", en: "to situate" },
  { sp: "tatuar", en: "to tattoo" },
  { sp: "valuar", en: "to value" },
];

export const guarVerbs = [
  { sp: "aguar", en: "to water" },
  { sp: "amenguar", en: "to lessen, diminish" },
  { sp: "amortiguar", en: "to muffle, cushion" },
  { sp: "apaciguar", en: "to appease" },
  { sp: "atestiguar", en: "to testify" },
  { sp: "averiguar", en: "to find out" },
  { sp: "desaguar", en: "to drain" },
  { sp: "fraguar", en: "to forge, harden" },
  { sp: "menguar", en: "to decrease" },
  { sp: "santiguar", en: "to bless" },
];

export const cuarVerbs = [
  { sp: "adecuar", en: "to adapt" },
  { sp: "anticuar", en: "to antiquate, outdate" },
  { sp: "colicuar", en: "to melt, dissolve" },
  { sp: "evacuar", en: "to evacuate" },
  { sp: "licuar", en: "to blend, liquify" },
  { sp: "oblicuar", en: "to slant, tilt, deviate" },
  { sp: "promiscuar", en: "to do two things simultaneously" },
];
